import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { cookies } from "next/headers";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const cookieStore = cookies();
    const themeCookie = cookieStore.get("theme");
    const theme = !themeCookie ? "light" : themeCookie.value;

    return (
        <html lang="en" className={theme} style={{ colorScheme: theme }}>
            <body className={inter.className}>
                <Providers>
                    <main className="flex min-h-screen flex-col bg-white dark:bg-black">
                        <Navbar />
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
